repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    #      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '.*\.ipynb'
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--profile",
            "black",
            "-a",
            "from __future__ import annotations",
            "--append-only",
          ]
        exclude: "^slurm/.*"
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        verbose: true
  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: 'v0.971'
  #     hooks:
  #      -   id: mypy
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.4"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]
        exclude: '.*\.ipynb'
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: ["--extra-keys", "cell.metadata.pycharm"]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

ci:
  autoupdate_schedule: monthly
  autofix_prs: false
