name: gnn
channels:
  - pyg
  - pytorch
  - ostrokach-forge
  - conda-forge
  - scikit-learn
dependencies:
  - python >= 3.10
  - cudatoolkit >= 11.8
  - pytorch >= 2
  - pytorch-scatter
  - pytorch-sparse
  - pyg
  - optuna
  - wandb
  - numpy
  - pandas < 2.0
  - scikit-learn
  - pip
