name: gnn
channels:
  # These do NOT commute!
  - pytorch
  - nvidia
  - pyg
  - ostrokach-forge
  - conda-forge
  - scikit-learn
dependencies:
  - python >= 3.10
  - pytorch >= 2
  - pytorch-cuda >= 11.8
  - pyg
  - optuna
  - wandb
  - numpy
  - pandas < 2.0
  - scikit-learn
  - pip
  - jupyter
