train:
  dirs:
    - /Users/fuchur/tmp/truth_cut_graphs_for_gsoc/part_1_0/
  stop: 5
test:
  dirs:
    - /Users/fuchur/tmp/truth_cut_graphs_for_gsoc/part_1_0/
  stop: 5
val:
  dirs:
    - /Users/fuchur/tmp/truth_cut_graphs_for_gsoc/part_1_0/
  stop: 5
