name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Smoke test
        run: python -c "import torch; print(torch.__version__)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[testing]
      - name: Test with pytest
        run: |
          pytest
      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
