name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # See https://stackoverflow.com/questions/72703363
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environments/testing-linux-64.lock
          environment-name: anaconda-client-env
      - name: Get date for cache timestamp
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache Conda env
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('environments/testing-linux-64.lock') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
      - name: Update environment if not cached
        run: micromamba create -n anaconda-client-env -f environments/testing-linux-64.lock
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Pip install package
        run: |
          python -m pip install --upgrade pip
          pip install .[testing]
      - name: Test with pytest
        run: |
          pytest
      - name: Explicitly convert coverage to xml
        run: coverage xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.1
