name: Python package

on: [push]

jobs:
  build:
    # See https://stackoverflow.com/questions/72703363
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: test
          environment-file: environment_testing.yml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[testing]
      - name: Test with pytest
        run: |
          pytest
      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
